### ISSUE TITLE
can't find jenkins wiki page for this plugin

### ISSUE THREAD

**Issue by adrianlop** [iverberk/jenkins-nomad#1]
please can you provide URL?
search doesn't find anything with "nomad"

**Comment by iverberk** [comment]
Hi adrianlop, I'm waiting for the Jenkins maintainers to approve my request. Until then you could take a look at https://github.com/iverberk/nomad-ci. It contains a compiled version of the plugin and a description how to use it. Once the plugin is approved I can add the link.

**Comment by adrianlop** [comment]
great, thanks!
