### ISSUE TITLE
Host os contraints

### ISSUE THREAD

**Issue by asanami** [iverberk/jenkins-nomad#4]
Is there a capability to support different target operating systems for jenkin plans through this plugin?  I couldn't find an obvious way to do it.

Thanks
Alex

**Comment by iverberk** [comment]
Hi Alex,

This plugin runs either a java or docker Jenkins slave with Nomad. Why is the operating system important to you? Normally you would run Nomad on Windows, OSX or Linux and it will take care of running the Jenkins slave job.

Regards,
Ivo

**Comment by iverberk** [comment]
@asanami I'll close this issue for now, if you have more information I'll take a look again.
