### ISSUE TITLE
region and datacenter parameters not working

### ISSUE THREAD

**Issue by adrianlop** [iverberk/jenkins-nomad#5]
hi @iverberk !
I think region param is not working. My nomad cluster region is "global". I set this param in the jenkins plugin to "whatever" and it continues allocating the job on my global region.

Also, datacenter param is not configurable, it is set to "dc1" by default, so I can't choose between my DCs.

Am I doing something wrong? can you take a look please?
If it's a bug, maybe some colleague of mine can make a PR.
thanks!

**Comment by iverberk** [comment]
Hi Adrian! Now that HashiConf EU is done and I'm back from vacation I'll take a look tonight :-) We probably need to expose more variables in the Jenkins interface but that's not hard to do. The region param is interesting, I'll test that as well.

**Comment by adrianlop** [comment]
thank you man!
could you please consider introducing `privileged` and `network mode (host, bridge...)` params in the plugin config too? would be great for some use cases I have in mind.

**Comment by iverberk** [comment]
@adrianlop I added the dc parameters. The region parameter actually needs to be passed as a get parameter. I fixed this as well.

Will look at the privileged and network mode this week.

**Comment by adrianlop** [comment]
great Ivo, thanks!! I appreciate it.

**Comment by adrianlop** [comment]
hi Ivo, did you manage to take a look at this? I don't wanna rush you, just asking :P

**Comment by iverberk** [comment]
@adrianlop way too late but I just added the options in https://github.com/jenkinsci/nomad-plugin/commit/32a5d5f636f85d303d2ec9e49fcca2097212d7f3 . I'll try to release today. I want to wait a little bit for another pull-request that's still pending. Apologies for the long delay, will try to maintain it a bit better. I did create a nice UI in the mean-time though ;-)

**Comment by adrianlop** [comment]
@iverberk thanks a lot! I'll deploy it asap.
btw I saw yesterday your Nomad UI project, it's awesome. great job man.
I'll try it out too :D

**Comment by iverberk** [comment]
@adrianlop I just released 0.2. Let me know if you have any more issues.
